# Bin2C.cmake - Convert binary file to C source
# This script emulates the ffbuild/bin2c.c functionality
#
# Expected variables:
#   INPUT_FILE  - Path to input binary file
#   OUTPUT_FILE - Path to output C source file
#   VAR_NAME    - Variable name prefix (e.g., "graph_html" -> ff_graph_html_data)

# Read the binary file
file(READ "${INPUT_FILE}" file_content HEX)

# Get file length
string(LENGTH "${file_content}" hex_length)
math(EXPR length "${hex_length} / 2")

# Convert hex string to C array format
set(array_content "")
set(i 0)
while(i LESS hex_length)
    string(SUBSTRING "${file_content}" ${i} 2 byte)
    string(APPEND array_content "0x${byte}, ")
    math(EXPR i "${i} + 2")
endwhile()

# Write the C source file
file(WRITE "${OUTPUT_FILE}"
"/* Generated by CMake Bin2C - do not edit! */
const unsigned char ff_${VAR_NAME}_data[] = { ${array_content}0x00 };
const unsigned int ff_${VAR_NAME}_len = ${length};
")
