# FFmpegExternalLibs.cmake
# Third-party library detection and configuration

include(CMakeFindDependencyMacro)
find_package(PkgConfig QUIET)

message(STATUS "Detecting external libraries...")

# ============================================================================
# Macro for external library detection
# ============================================================================
macro(ffmpeg_find_external_lib option_name pkg_name config_var)
    option(${option_name} "Enable ${pkg_name}" ON)
    if(${option_name})
        pkg_check_modules(${config_var} QUIET IMPORTED_TARGET ${pkg_name})
        if(${config_var}_FOUND)
            set(CONFIG_${config_var} 1)
            set(HAVE_${config_var} 1)
            message(STATUS "Found ${pkg_name}: YES (${${config_var}_VERSION})")
        else()
            set(CONFIG_${config_var} 0)
            set(HAVE_${config_var} 0)
            message(STATUS "Found ${pkg_name}: NO")
        endif()
    else()
        set(CONFIG_${config_var} 0)
        set(HAVE_${config_var} 0)
        message(STATUS "${pkg_name}: disabled by option")
    endif()
endmacro()

# ============================================================================
# P0: Core libraries
# ============================================================================

# zlib
option(ENABLE_ZLIB "Enable zlib" ON)
if(ENABLE_ZLIB)
    find_package(ZLIB QUIET)
    if(ZLIB_FOUND)
        set(CONFIG_ZLIB 1)
        set(HAVE_ZLIB 1)
        message(STATUS "Found zlib: YES (${ZLIB_VERSION_STRING})")
    else()
        set(CONFIG_ZLIB 0)
        set(HAVE_ZLIB 0)
        message(STATUS "Found zlib: NO")
    endif()
else()
    set(CONFIG_ZLIB 0)
    set(HAVE_ZLIB 0)
endif()

# bzlib (bzip2)
option(ENABLE_BZLIB "Enable bzlib" ON)
if(ENABLE_BZLIB)
    find_package(BZip2 QUIET)
    if(BZIP2_FOUND)
        set(CONFIG_BZLIB 1)
        set(HAVE_BZLIB 1)
        message(STATUS "Found bzlib: YES (${BZIP2_VERSION_STRING})")
    else()
        set(CONFIG_BZLIB 0)
        set(HAVE_BZLIB 0)
        message(STATUS "Found bzlib: NO")
    endif()
else()
    set(CONFIG_BZLIB 0)
    set(HAVE_BZLIB 0)
endif()

# lzma
option(ENABLE_LZMA "Enable lzma" ON)
if(ENABLE_LZMA)
    find_package(LibLZMA QUIET)
    if(LIBLZMA_FOUND)
        set(CONFIG_LZMA 1)
        set(HAVE_LZMA 1)
        message(STATUS "Found lzma: YES (${LIBLZMA_VERSION_STRING})")
    else()
        set(CONFIG_LZMA 0)
        set(HAVE_LZMA 0)
        message(STATUS "Found lzma: NO")
    endif()
else()
    set(CONFIG_LZMA 0)
    set(HAVE_LZMA 0)
endif()

# iconv
option(ENABLE_ICONV "Enable iconv" ON)
if(ENABLE_ICONV)
    find_package(Iconv QUIET)
    if(Iconv_FOUND)
        set(CONFIG_ICONV 1)
        set(HAVE_ICONV 1)
        message(STATUS "Found iconv: YES")
    else()
        set(CONFIG_ICONV 0)
        set(HAVE_ICONV 0)
        message(STATUS "Found iconv: NO")
    endif()
else()
    set(CONFIG_ICONV 0)
    set(HAVE_ICONV 0)
endif()

# ============================================================================
# P1: Security and encryption
# ============================================================================

# OpenSSL
option(ENABLE_OPENSSL "Enable OpenSSL" OFF)
if(ENABLE_OPENSSL)
    find_package(OpenSSL QUIET)
    if(OpenSSL_FOUND)
        set(CONFIG_OPENSSL 1)
        set(HAVE_OPENSSL 1)
        set(USING_TLS_LIBRARY "openssl")
        message(STATUS "Found OpenSSL: YES (${OPENSSL_VERSION})")
    else()
        set(CONFIG_OPENSSL 0)
        set(HAVE_OPENSSL 0)
        message(STATUS "Found OpenSSL: NO")
    endif()
else()
    set(CONFIG_OPENSSL 0)
    set(HAVE_OPENSSL 0)
endif()

# GnuTLS (only if OpenSSL not found)
if(NOT CONFIG_OPENSSL)
    option(ENABLE_GNUTLS "Enable GnuTLS" ON)
    if(ENABLE_GNUTLS)
        pkg_check_modules(GNUTLS QUIET IMPORTED_TARGET gnutls)
        if(GNUTLS_FOUND)
            set(CONFIG_GNUTLS 1)
            set(HAVE_GNUTLS 1)
            set(USING_TLS_LIBRARY "gnutls")
            message(STATUS "Found GnuTLS: YES (${GNUTLS_VERSION})")
        else()
            set(CONFIG_GNUTLS 0)
            set(HAVE_GNUTLS 0)
            message(STATUS "Found GnuTLS: NO")
        endif()
    else()
        set(CONFIG_GNUTLS 0)
        set(HAVE_GNUTLS 0)
    endif()
else()
    # OpenSSL takes priority, disable GnuTLS
    set(CONFIG_GNUTLS 0)
    set(HAVE_GNUTLS 0)
endif()

# libxml2
option(ENABLE_LIBXML2 "Enable libxml2" ON)
if(ENABLE_LIBXML2)
    find_package(LibXml2 QUIET)
    if(LIBXML2_FOUND)
        set(CONFIG_LIBXML2 1)
        set(HAVE_LIBXML2 1)
        message(STATUS "Found libxml2: YES (${LIBXML2_VERSION_STRING})")
    else()
        set(CONFIG_LIBXML2 0)
        set(HAVE_LIBXML2 0)
        message(STATUS "Found libxml2: NO")
    endif()
else()
    set(CONFIG_LIBXML2 0)
    set(HAVE_LIBXML2 0)
endif()

# ============================================================================
# P1: External codecs
# ============================================================================

# x264
option(ENABLE_LIBX264 "Enable x264 encoder" ON)
if(ENABLE_LIBX264)
    pkg_check_modules(X264 QUIET IMPORTED_TARGET x264)
    if(X264_FOUND)
        set(CONFIG_LIBX264 1)
        message(STATUS "Found x264: YES (${X264_VERSION})")
    else()
        set(CONFIG_LIBX264 0)
        message(STATUS "Found x264: NO")
    endif()
else()
    set(CONFIG_LIBX264 0)
    message(STATUS "x264: disabled by option")
endif()

# x265
option(ENABLE_LIBX265 "Enable x265 encoder" ON)
if(ENABLE_LIBX265)
    pkg_check_modules(X265 QUIET IMPORTED_TARGET x265)
    if(X265_FOUND)
        set(CONFIG_LIBX265 1)
        message(STATUS "Found x265: YES (${X265_VERSION})")
    else()
        set(CONFIG_LIBX265 0)
        message(STATUS "Found x265: NO")
    endif()
else()
    set(CONFIG_LIBX265 0)
    message(STATUS "x265: disabled by option")
endif()

# libaom (AV1)
option(ENABLE_LIBAOM "Enable libaom AV1 codec" ON)
if(ENABLE_LIBAOM)
    pkg_check_modules(AOM QUIET IMPORTED_TARGET aom)
    if(AOM_FOUND)
        set(CONFIG_LIBAOM 1)
        message(STATUS "Found libaom: YES (${AOM_VERSION})")
    else()
        set(CONFIG_LIBAOM 0)
        message(STATUS "Found libaom: NO")
    endif()
else()
    set(CONFIG_LIBAOM 0)
    message(STATUS "libaom: disabled by option")
endif()

# libdav1d (AV1 decoder)
option(ENABLE_LIBDAV1D "Enable libdav1d AV1 decoder" ON)
if(ENABLE_LIBDAV1D)
    pkg_check_modules(DAV1D QUIET IMPORTED_TARGET dav1d)
    if(DAV1D_FOUND)
        set(CONFIG_LIBDAV1D 1)
        message(STATUS "Found libdav1d: YES (${DAV1D_VERSION})")
    else()
        set(CONFIG_LIBDAV1D 0)
        message(STATUS "Found libdav1d: NO")
    endif()
else()
    set(CONFIG_LIBDAV1D 0)
    message(STATUS "libdav1d: disabled by option")
endif()

# libvpx (VP8/VP9)
option(ENABLE_LIBVPX "Enable libvpx VP8/VP9 codec" ON)
if(ENABLE_LIBVPX)
    pkg_check_modules(VPX QUIET IMPORTED_TARGET vpx)
    if(VPX_FOUND)
        set(CONFIG_LIBVPX 1)
        message(STATUS "Found libvpx: YES (${VPX_VERSION})")
    else()
        set(CONFIG_LIBVPX 0)
        message(STATUS "Found libvpx: NO")
    endif()
else()
    set(CONFIG_LIBVPX 0)
    message(STATUS "libvpx: disabled by option")
endif()

# libmp3lame
option(ENABLE_LIBMP3LAME "Enable libmp3lame MP3 encoder" ON)
if(ENABLE_LIBMP3LAME)
    pkg_check_modules(MP3LAME QUIET IMPORTED_TARGET lame)
    if(MP3LAME_FOUND)
        set(CONFIG_LIBMP3LAME 1)
        message(STATUS "Found libmp3lame: YES (${MP3LAME_VERSION})")
    else()
        set(CONFIG_LIBMP3LAME 0)
        message(STATUS "Found libmp3lame: NO")
    endif()
else()
    set(CONFIG_LIBMP3LAME 0)
    message(STATUS "libmp3lame: disabled by option")
endif()

# libopus
option(ENABLE_LIBOPUS "Enable libopus codec" ON)
if(ENABLE_LIBOPUS)
    pkg_check_modules(OPUS QUIET IMPORTED_TARGET opus)
    if(OPUS_FOUND)
        set(CONFIG_LIBOPUS 1)
        message(STATUS "Found libopus: YES (${OPUS_VERSION})")
    else()
        set(CONFIG_LIBOPUS 0)
        message(STATUS "Found libopus: NO")
    endif()
else()
    set(CONFIG_LIBOPUS 0)
    message(STATUS "libopus: disabled by option")
endif()

# libvorbis
option(ENABLE_LIBVORBIS "Enable libvorbis codec" ON)
if(ENABLE_LIBVORBIS)
    pkg_check_modules(VORBIS QUIET IMPORTED_TARGET vorbis)
    if(VORBIS_FOUND)
        set(CONFIG_LIBVORBIS 1)
        message(STATUS "Found libvorbis: YES (${VORBIS_VERSION})")
    else()
        set(CONFIG_LIBVORBIS 0)
        message(STATUS "Found libvorbis: NO")
    endif()
else()
    set(CONFIG_LIBVORBIS 0)
    message(STATUS "libvorbis: disabled by option")
endif()

# libfdk-aac
option(ENABLE_LIBFDK_AAC "Enable libfdk-aac codec" ON)
if(ENABLE_LIBFDK_AAC)
    pkg_check_modules(FDK_AAC QUIET IMPORTED_TARGET fdk-aac)
    if(FDK_AAC_FOUND)
        set(CONFIG_LIBFDK_AAC 1)
        message(STATUS "Found libfdk-aac: YES (${FDK_AAC_VERSION})")
    else()
        set(CONFIG_LIBFDK_AAC 0)
        message(STATUS "Found libfdk-aac: NO")
    endif()
else()
    set(CONFIG_LIBFDK_AAC 0)
    message(STATUS "libfdk-aac: disabled by option")
endif()

# ============================================================================
# P2: Advanced codecs
# ============================================================================

# libsvtav1
option(ENABLE_LIBSVTAV1 "Enable SVT-AV1 encoder" ON)
if(ENABLE_LIBSVTAV1)
    pkg_check_modules(SVTAV1 QUIET IMPORTED_TARGET SvtAv1Enc)
    if(SVTAV1_FOUND)
        set(CONFIG_LIBSVTAV1 1)
        message(STATUS "Found SVT-AV1: YES (${SVTAV1_VERSION})")
    else()
        set(CONFIG_LIBSVTAV1 0)
        message(STATUS "Found SVT-AV1: NO")
    endif()
else()
    set(CONFIG_LIBSVTAV1 0)
    message(STATUS "SVT-AV1: disabled by option")
endif()

# libvvenc (VVC encoder)
option(ENABLE_LIBVVENC "Enable VVC encoder" ON)
if(ENABLE_LIBVVENC)
    pkg_check_modules(VVENC QUIET IMPORTED_TARGET libvvenc)
    if(VVENC_FOUND)
        set(CONFIG_LIBVVENC 1)
        message(STATUS "Found libvvenc: YES (${VVENC_VERSION})")
    else()
        set(CONFIG_LIBVVENC 0)
        message(STATUS "Found libvvenc: NO")
    endif()
else()
    set(CONFIG_LIBVVENC 0)
    message(STATUS "libvvenc: disabled by option")
endif()

# ============================================================================
# P3: Hardware acceleration
# ============================================================================

# Vulkan
option(ENABLE_VULKAN "Enable Vulkan support" ON)
if(ENABLE_VULKAN)
    find_package(Vulkan QUIET)
    if(Vulkan_FOUND)
        set(CONFIG_VULKAN 1)
        set(HAVE_VULKAN 1)
        message(STATUS "Found Vulkan: YES")
    else()
        set(CONFIG_VULKAN 0)
        set(HAVE_VULKAN 0)
        message(STATUS "Found Vulkan: NO")
    endif()
else()
    set(CONFIG_VULKAN 0)
    set(HAVE_VULKAN 0)
endif()

# CUDA
option(ENABLE_CUDA "Enable CUDA support" ON)
if(ENABLE_CUDA)
    find_package(CUDA QUIET)
    if(CUDA_FOUND)
        set(CONFIG_CUDA 1)
        set(HAVE_CUDA 1)
        message(STATUS "Found CUDA: YES")
    else()
        set(CONFIG_CUDA 0)
        set(HAVE_CUDA 0)
        message(STATUS "Found CUDA: NO")
    endif()
else()
    set(CONFIG_CUDA 0)
    set(HAVE_CUDA 0)
endif()

# ============================================================================
# P3: Video processing
# ============================================================================

# SDL2 (for ffplay)
option(ENABLE_SDL2 "Enable SDL2 support" ON)
if(ENABLE_SDL2)
    find_package(SDL2 QUIET)
    if(SDL2_FOUND)
        set(CONFIG_SDL2 1)
        set(HAVE_SDL2 1)
        message(STATUS "Found SDL2: YES")
    else()
        set(CONFIG_SDL2 0)
        set(HAVE_SDL2 0)
        message(STATUS "Found SDL2: NO")
    endif()
else()
    set(CONFIG_SDL2 0)
    set(HAVE_SDL2 0)
endif()

# libass (subtitle rendering)
option(ENABLE_LIBASS "Enable libass" ON)
if(ENABLE_LIBASS)
    pkg_check_modules(ASS QUIET IMPORTED_TARGET libass)
    if(ASS_FOUND)
        set(CONFIG_LIBASS 1)
        message(STATUS "Found libass: YES (${ASS_VERSION})")
    else()
        set(CONFIG_LIBASS 0)
        message(STATUS "Found libass: NO")
    endif()
else()
    set(CONFIG_LIBASS 0)
    message(STATUS "libass: disabled by option")
endif()

# libzimg
option(ENABLE_LIBZIMG "Enable libzimg" ON)
if(ENABLE_LIBZIMG)
    pkg_check_modules(ZIMG QUIET IMPORTED_TARGET zimg)
    if(ZIMG_FOUND)
        set(CONFIG_LIBZIMG 1)
        message(STATUS "Found libzimg: YES (${ZIMG_VERSION})")
    else()
        set(CONFIG_LIBZIMG 0)
        message(STATUS "Found libzimg: NO")
    endif()
else()
    set(CONFIG_LIBZIMG 0)
    message(STATUS "libzimg: disabled by option")
endif()

# ============================================================================
# Font and text rendering
# ============================================================================

# FreeType
option(ENABLE_LIBFREETYPE "Enable FreeType" ON)
if(ENABLE_LIBFREETYPE)
    find_package(Freetype QUIET)
    if(Freetype_FOUND)
        set(CONFIG_LIBFREETYPE 1)
        message(STATUS "Found FreeType: YES")
    else()
        set(CONFIG_LIBFREETYPE 0)
        message(STATUS "Found FreeType: NO")
    endif()
else()
    set(CONFIG_LIBFREETYPE 0)
    message(STATUS "FreeType: disabled by option")
endif()

# Fontconfig
option(ENABLE_LIBFONTCONFIG "Enable Fontconfig" ON)
if(ENABLE_LIBFONTCONFIG)
    pkg_check_modules(FONTCONFIG QUIET IMPORTED_TARGET fontconfig)
    if(FONTCONFIG_FOUND)
        set(CONFIG_LIBFONTCONFIG 1)
        message(STATUS "Found Fontconfig: YES (${FONTCONFIG_VERSION})")
    else()
        set(CONFIG_LIBFONTCONFIG 0)
        message(STATUS "Found Fontconfig: NO")
    endif()
else()
    set(CONFIG_LIBFONTCONFIG 0)
    message(STATUS "Fontconfig: disabled by option")
endif()

# VAAPI (Video Acceleration API) - Linux hardware acceleration
if(UNIX AND NOT APPLE)
    pkg_check_modules(LIBVA QUIET IMPORTED_TARGET libva)
    if(LIBVA_FOUND)
        set(VAAPI_FOUND TRUE)
        set(VAAPI_LIBRARIES ${LIBVA_LIBRARIES})
        set(VAAPI_INCLUDE_DIRS ${LIBVA_INCLUDE_DIRS})
        message(STATUS "Found VAAPI (libva): YES (${LIBVA_VERSION})")
    else()
        set(VAAPI_FOUND FALSE)
        message(STATUS "Found VAAPI (libva): NO")
    endif()
else()
    set(VAAPI_FOUND FALSE)
endif()

# ============================================================================
# macOS specific
# ============================================================================

if(APPLE)
    # AVFoundation
    check_include_file("AVFoundation/AVFoundation.h" HAVE_AVFOUNDATION)
    if(HAVE_AVFOUNDATION)
        set(CONFIG_AVFOUNDATION 1)
        message(STATUS "AVFoundation: YES")
    else()
        set(CONFIG_AVFOUNDATION 0)
        message(STATUS "AVFoundation: NO")
    endif()
    
    # CoreVideo
    set(CONFIG_COREIMAGE 0)  # deprecated
    set(CONFIG_APPKIT 1)
    set(CONFIG_SECURETRANSPORT 0)  # Use OpenSSL instead
endif()

# ============================================================================
# Linux specific
# ============================================================================

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    # ALSA
    pkg_check_modules(ALSA QUIET IMPORTED_TARGET alsa)
    if(ALSA_FOUND)
        set(CONFIG_ALSA 1)
        message(STATUS "Found ALSA: YES (${ALSA_VERSION})")
    else()
        set(CONFIG_ALSA 0)
        message(STATUS "Found ALSA: NO")
    endif()
    
    # V4L2
    check_include_file("linux/videodev2.h" HAVE_LINUX_VIDEODEV2_H)
    if(HAVE_LINUX_VIDEODEV2_H)
        set(CONFIG_V4L2_M2M 1)
    else()
        set(CONFIG_V4L2_M2M 0)
    endif()
endif()

# ============================================================================
# Network
# ============================================================================

# Network support
set(CONFIG_NETWORK 1)

# libsrtp
option(ENABLE_LIBSRTP "Enable libsrtp" ON)
if(ENABLE_LIBSRTP)
    pkg_check_modules(SRTP QUIET IMPORTED_TARGET libsrtp2)
    if(SRTP_FOUND)
        set(CONFIG_LIBSRTP 1)
        message(STATUS "Found libsrtp2: YES (${SRTP_VERSION})")
    else()
        set(CONFIG_LIBSRTP 0)
        message(STATUS "Found libsrtp2: NO")
    endif()
else()
    set(CONFIG_LIBSRTP 0)
endif()

message(STATUS "External library detection complete")
