# FFmpeg Component Lists Generator
# Scans source files to generate muxer_list.c, demuxer_list.c, protocol_list.c, etc.

message(STATUS "Generating component lists...")

# ============================================================================
# Scan functions
# ============================================================================

function(ffmpeg_scan_muxers SOURCE_DIR OUTPUT_FILE)
    # Scan all .c files for FFOutputFormat definitions
    file(GLOB SOURCES "${SOURCE_DIR}/*.c")
    set(MUXER_LIST "")
    foreach(SRC ${SOURCES})
        file(READ ${SRC} CONTENT)
        # Match patterns like: const FFOutputFormat ff_xxx_muxer
        string(REGEX MATCHALL "const[ \t]+FFOutputFormat[ \t]+ff_([a-z0-9_]+)_muxer" MATCHES "${CONTENT}")
        foreach(MATCH ${MATCHES})
            string(REGEX REPLACE "const[ \t]+FFOutputFormat[ \t]+ff_([a-z0-9_]+)_muxer" "\\1" MUXER_NAME "${MATCH}")
            # Exclude test muxers
            if(NOT MUXER_NAME MATCHES ".*_test$")
                list(APPEND MUXER_LIST "ff_${MUXER_NAME}_muxer")
            endif()
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES MUXER_LIST)
    list(SORT MUXER_LIST)
    
    # Generate the list file with extern declarations
    set(LIST_CONTENT "/* Auto-generated by CMake - do not edit */\n")
    string(APPEND LIST_CONTENT "#include \"libavformat/internal.h\"\n\n")
    # Add extern declarations
    foreach(MUXER ${MUXER_LIST})
        string(APPEND LIST_CONTENT "extern const FFOutputFormat ${MUXER};\n")
    endforeach()
    string(APPEND LIST_CONTENT "\nstatic const FFOutputFormat * const muxer_list[] = {\n")
    foreach(MUXER ${MUXER_LIST})
        string(APPEND LIST_CONTENT "    &${MUXER},\n")
    endforeach()
    string(APPEND LIST_CONTENT "    NULL\n};\n")
    file(WRITE ${OUTPUT_FILE} "${LIST_CONTENT}")
    message(STATUS "Generated muxer_list.c with ${MUXER_LIST}")
endfunction()

function(ffmpeg_scan_demuxers SOURCE_DIR OUTPUT_FILE)
    # Scan all .c files for FFInputFormat definitions
    file(GLOB SOURCES "${SOURCE_DIR}/*.c")
    set(DEMUXER_LIST "")
    foreach(SRC ${SOURCES})
        file(READ ${SRC} CONTENT)
        # Match patterns like: const FFInputFormat ff_xxx_demuxer
        string(REGEX MATCHALL "const[ \t]+FFInputFormat[ \t]+ff_([a-z0-9_]+)_demuxer" MATCHES "${CONTENT}")
        foreach(MATCH ${MATCHES})
            string(REGEX REPLACE "const[ \t]+FFInputFormat[ \t]+ff_([a-z0-9_]+)_demuxer" "\\1" DEMUXER_NAME "${MATCH}")
            list(APPEND DEMUXER_LIST "ff_${DEMUXER_NAME}_demuxer")
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES DEMUXER_LIST)
    list(SORT DEMUXER_LIST)
    
    # Generate the list file with extern declarations
    set(LIST_CONTENT "/* Auto-generated by CMake - do not edit */\n")
    string(APPEND LIST_CONTENT "#include \"libavformat/internal.h\"\n\n")
    # Add extern declarations
    foreach(DEMUXER ${DEMUXER_LIST})
        string(APPEND LIST_CONTENT "extern const FFInputFormat ${DEMUXER};\n")
    endforeach()
    string(APPEND LIST_CONTENT "\nstatic const FFInputFormat * const demuxer_list[] = {\n")
    foreach(DEMUXER ${DEMUXER_LIST})
        string(APPEND LIST_CONTENT "    &${DEMUXER},\n")
    endforeach()
    string(APPEND LIST_CONTENT "    NULL\n};\n")
    file(WRITE ${OUTPUT_FILE} "${LIST_CONTENT}")
    message(STATUS "Generated demuxer_list.c with ${DEMUXER_LIST}")
endfunction()

function(ffmpeg_scan_protocols SOURCE_DIR OUTPUT_FILE)
    # Scan all .c files for URLProtocol definitions
    file(GLOB SOURCES "${SOURCE_DIR}/*.c")
    set(PROTOCOL_LIST "")
    foreach(SRC ${SOURCES})
        file(READ ${SRC} CONTENT)
        # Match patterns like: const URLProtocol ff_xxx_protocol
        string(REGEX MATCHALL "const[ \t]+URLProtocol[ \t]+ff_([a-z0-9_]+)_protocol" MATCHES "${CONTENT}")
        foreach(MATCH ${MATCHES})
            string(REGEX REPLACE "const[ \t]+URLProtocol[ \t]+ff_([a-z0-9_]+)_protocol" "\\1" PROTO_NAME "${MATCH}")
            list(APPEND PROTOCOL_LIST "ff_${PROTO_NAME}_protocol")
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES PROTOCOL_LIST)
    list(SORT PROTOCOL_LIST)
    
    # Generate the list file with extern declarations
    set(LIST_CONTENT "/* Auto-generated by CMake - do not edit */\n")
    string(APPEND LIST_CONTENT "#include \"libavformat/url.h\"\n\n")
    # Add extern declarations
    foreach(PROTO ${PROTOCOL_LIST})
        string(APPEND LIST_CONTENT "extern const URLProtocol ${PROTO};\n")
    endforeach()
    string(APPEND LIST_CONTENT "\nstatic const URLProtocol * const url_protocols[] = {\n")
    foreach(PROTO ${PROTOCOL_LIST})
        string(APPEND LIST_CONTENT "    &${PROTO},\n")
    endforeach()
    string(APPEND LIST_CONTENT "    NULL\n};\n")
    file(WRITE ${OUTPUT_FILE} "${LIST_CONTENT}")
    message(STATUS "Generated protocol_list.c with ${PROTOCOL_LIST}")
endfunction()

# ============================================================================
# Convenience function to generate all libavformat lists
# ============================================================================

function(ffmpeg_generate_avformat_lists SOURCE_DIR OUTPUT_DIR)
    if(NOT EXISTS ${OUTPUT_DIR})
        file(MAKE_DIRECTORY ${OUTPUT_DIR})
    endif()
    
    ffmpeg_scan_muxers(${SOURCE_DIR} "${OUTPUT_DIR}/muxer_list.c")
    ffmpeg_scan_demuxers(${SOURCE_DIR} "${OUTPUT_DIR}/demuxer_list.c")
    ffmpeg_scan_protocols(${SOURCE_DIR} "${OUTPUT_DIR}/protocol_list.c")
endfunction()
